[workspace]
resolver = "2"
exclude = [
  "tests/fixture/failure",
  "tests/fixture/state",
  "tests/fixture/success",
  "dev",
]
members = [
  "gen-dev-cargo-toml",
]

[workspace.package]
version = "6.0.0"
authors = [
  "Liv <mokou@fastmail.com>",
  "Carol (Nichols || Goulding) <carol.nichols@gmail.com>",
]
license = "MIT"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.82"
serde = { version = "1.0.197", features = ["derive"] }
toml_edit = { version = "0.22.9", default-features = false, features = ["parse", "serde"] }

[package]
name = "rustlings"
description = "Small exercises to get you used to reading and writing Rust code!"
default-run = "rustlings"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
hashbrown = "0.14.3"
notify-debouncer-mini = "0.4.1"
ratatui = "0.26.2"
rustlings-macros = { path = "rustlings-macros" }
serde.workspace = true
toml_edit.workspace = true
which = "6.0.1"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
